sudo: required
services:
  - docker

before_install:
  - docker build -t vikramnagarkar/frontend-web -f frontend-web/Dockerfile.dev .

# -- is for npm to exit after running tests else it would just wait for our input which is default
script:
  - docker run vikramnagarkar/frontend-web npm run test -- --coverage
